
global:
  namespace: formulatel

# persist config
persist:
  image: formulatel/persist
  tag: latest
  replicas: 1
  mqtt_broker: 'tcp://formulatel-mosquitto:1883' # address to the MQTT broker that persist talks to

# db-migrate
migrate:
  enabled: true
  # for local development, we'll reuse a single secret that contains the superuser credentials
  db_secret_name: formulatel-db-user-persist
  image: formulatel/timescaledb-migrations
  tag: latest

# configuration values used in multiple templates
# db values
db:
  name: postgres

ssl:
  enabled: false

# grafana_ingress sets up an Ingress to allow web traffic into our `formulatel-grafana` service
grafana_ingress:
  enabled: false

mqtt_ingress:
  enabled: false

# sub-chart values

grafana:
  plugins:
    - grafana-mqtt-datasource

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: formulatel_mqtt
          type: grafana-mqtt-datasource
          jsonData:
            uri: "tcp://formulatel-mosquitto:1883"
            tlsAuth: false
            clientID: formulatel_grafana
            isDefault: true
        - name: formulatel_psql
          type: postgres
          url: timescaledb:5432
          user: postgres
          secureJsonData:
            password: 'postgres'
          jsonData:
            database: postgres
            sslmode: 'disable'
            maxOpenConns: 100
            maxIdleConns: 100
            maxIdleConnsAuto: true
            connMaxLifetime: 14400
            postgresVersion: 1800
            timescaledb: true
        - name: formulatel_jaeger
          type: jaeger
          url: http://jaeger:16686

  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Admin

    adminUser: grafana
    adminPassword: grafana

    database:
      type: postgres
      ssl_mode: disable
      instrument_queries: true
      host: 'timescaledb:5432'
      name: postgres
      user: postgres

  envValueFrom:
    GF_DATABASE_USER:
      secretKeyRef:
        name: formulatel-db-user-persist
        key: username

    GF_DATABASE_PASSWORD:
      secretKeyRef:
        name: formulatel-db-user-persist
        key: password

# mosquitto.conf
# [auth]
# Postgres Backend Configuration
# auth_plugin /path/to/mosquitto-go-auth.so
# auth_opt_backends postgres

# auth_opt_pg_host timescale-db #10.0.1.38 # resolves to the host machine where postgres
# auth_opt_pg_port 5432
# auth_opt_pg_dbname formulatel
# auth_opt_pg_user mosquitto_broker
# auth_opt_pg_password YourSecretPasswordFromK8sSecrets
# auth_opt_pg_sslmode disable

# Fetch the hash from the generic accounts table
# auth_opt_pg_userquery SELECT password_hash FROM auth.accounts WHERE username = $1 AND is_active = true LIMIT 1
# auth_opt_pg_superquery SELECT count(*) FROM auth.accounts WHERE username = $1 AND is_admin = true AND is_active = true

# Validate ACLs against the new foreign key
# auth_opt_pg_aclquery SELECT count(*) FROM auth.mqtt_acls acl JOIN auth.accounts user ON acl.account_id = user.id WHERE user.username = $1 AND $2 LIKE acl.topic AND (acl.access_level & $3) > 0

