apiVersion: v2
name: formulatel
description: A Helm chart that provisions `formulatel-persist`, the database migrations, Grafana, and mosquitto
type: application
version: 0.6.0
appVersion: "0.1.0"
dependencies:
  - name: grafana
    version: 12.7.2
    repository: oci://ghcr.io/grafana-community/helm-charts
  - name: app-template
    version: 5.0.1
    repository: oci://ghcr.io/bjw-s-labs/helm
