# formulatel chart values

# Global Configuration
global:
  namespace: formulatel

# Persist Component
persist:
  image: ghcr.io/isnor/formulatel/persist
  tag: main
  replicas: 1

# Migration Job configuration
migrate:
  enabled: true
  image: ghcr.io/isnor/formulatel/timescaledb-migrations
  tag: main

# configuration values used in multiple templates
# db values
db:
  name: postgres
