# formulatel chart values

# both persist and migrate require a specific secret to be available in kubernetes,
# so this probably isn't a good chart.
# TODO: create the database secret as part of the install, requiring the DB values to install the chart
# TODO: add tests for the chart

global:
  namespace: formulatel

# persist config
persist:
  image: ghcr.io/isnor/formulatel/persist
  tag: main
  replicas: 1
  mqtt_broker: 'tcp://mosquitto:1883' # address to the MQTT broker that persist talks to

# db-migrate
migrate:
  enabled: true
  image: ghcr.io/isnor/formulatel/timescaledb-migrations
  tag: main

# grafana - sets up an Ingress to allow web traffic into an existing Grafana service running in the cluster
# TODO: how heavily does this rely on traefik?
grafana:
  hostname: dashboard.formula.tel # host to route requests from
  port: 80 # port that Grafana exposes
  service_name: grafana # name of the grafana service deployed in the cluster

# configuration values used in multiple templates
# db values
db:
  name: postgres
