# formulatel chart values

# both persist and migrate require a specific secret to be available in kubernetes,
# so this probably isn't a good chart.
# TODO: create the database secret as part of the install, requiring the DB values to install the chart
# TODO: add tests for the chart

global:
  namespace: formulatel

# persist config
persist:
  image: ghcr.io/isnor/formulatel/persist
  tag: main
  replicas: 1
  mqtt_broker: 'tcp://formulatel-mosquitto:1883' # address to the MQTT broker that persist talks to

# db-migrate
migrate:
  enabled: true
  db_secret_name: formulatel-db-secrets
  image: ghcr.io/isnor/formulatel/timescaledb-migrations
  tag: main

# configuration values used in multiple templates
# db values
db:
  name: formulatel

ssl:
  enabled: true
  cluster_issuer: formulatel-formulatel-letsencrypt-issuer

# grafana_ingress sets up an Ingress to allow web traffic into our `formulatel-grafana` service
grafana_ingress:
  enabled: true
  hostname: dashboard.formula.tel # host to route requests from
  port: 80 # port that Grafana exposes
  service_name: formulatel-grafana # name of the grafana service deployed in the cluster

mqtt_ingress:
  enabled: true
  hostname: mqtt.formula.tel # host to route requests from
  port: 9001 # websocket port of mosquitto
  service_name: formulatel-mosquitto # name of the mqtt broker service deployed in the cluster