global:
  namespace: formulatel

# persist config
persist:
  image: formulatel/persist
  tag: latest
  replicas: 1
  mqtt_broker: 'tcp://formulatel-mosquitto:1883' # address to the MQTT broker that persist talks to

# db-migrate
migrate:
  enabled: true
  # this secret must exist and must have "username" and "password" fields
  db_secret_name: formulatel-db-user-persist
  image: formulatel/timescaledb-migrations
  tag: latest

# configuration values used in multiple templates
# db values
db:
  name: postgres

ssl:
  enabled: false

# grafana_ingress sets up an Ingress to allow web traffic into our `formulatel-grafana` service
grafana_ingress:
  enabled: false

mqtt_ingress:
  enabled: false

# sub-chart values

grafana:
  plugins:
    - grafana-mqtt-datasource

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: formulatel_mqtt
          type: grafana-mqtt-datasource
          jsonData:
            uri: "tcp://formulatel-mosquitto:1883"
            tlsAuth: false
            clientID: formulatel_grafana
            isDefault: true
        - name: formulatel_psql
          type: postgres
          url: timescaledb:5432
          user: postgres
          secureJsonData:
            password: 'postgres'
          jsonData:
            database: postgres
            sslmode: 'disable'
            maxOpenConns: 100
            maxIdleConns: 100
            maxIdleConnsAuto: true
            connMaxLifetime: 14400
            postgresVersion: 1800
            timescaledb: true
        - name: formulatel_jaeger
          type: jaeger
          url: http://jaeger:16686

  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Admin

    database:
      type: postgres
      ssl_mode: disable
      host: 'timescaledb:5432'
      name: postgres
      user: postgres
      password: postgres


app-template:
  configMaps:
    mosquitto-template:
      enabled: true
      data:
        mosquitto.conf.tmpl: |
          persistence true
          persistence_location /mosquitto/data/
          autosave_interval 1800
          per_listener_settings true

          listener 1883 0.0.0.0
          protocol mqtt
          allow_anonymous true

          listener 9001 0.0.0.0
          protocol websockets
          allow_anonymous false

          # Plugin Binding
          auth_plugin /mosquitto/go-auth.so
          auth_opt_log_level debug
          auth_opt_backends postgres

          # Postgres Integration
          auth_opt_pg_host timescaledb
          auth_opt_pg_port 5432
          auth_opt_pg_dbname postgres
          auth_opt_pg_user postgres
          auth_opt_pg_password postgres
          auth_opt_pg_sslmode disable

          # Queries
          auth_opt_pg_userquery SELECT password_hash FROM auth.accounts WHERE username = $1 LIMIT 1
          auth_opt_pg_superquery SELECT COUNT(*) FROM auth.accounts WHERE username = $1 AND is_admin = true
          auth_opt_pg_aclquery SELECT topic FROM auth.mqtt_acls JOIN auth.accounts ON mqtt_acls.account_id=accounts.id WHERE username = $1 AND (access_level >= $2)
          auth_opt_hasher bcrypt