grafana.ini:
  auth.anonymous:
    enabled: true
    org_role: Admin

plugins:
  - grafana-mqtt-datasource

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: formulatel_mqtt
        type: grafana-mqtt-datasource
        jsonData:
          uri: "tcp://mosquitto:1883"
          tlsAuth: false
          clientID: formulatel_grafana
          isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'formulatel'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/formulatel

dashboards:
  formulatel:
    test_dashboard:
      json: "" # TODO: this is kind of a hack; we're setting this using helm's `--set-file` flag, which we set in the Tiltfile
    live:
      json: "" # TODO: same hack as above. Have we tried using the Grafana k8s resource type?
