grafana.ini:
  auth.anonymous:
    enabled: true
    org_role: Admin

plugins:
  - grafana-mqtt-datasource

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: formulatel_mqtt
        type: grafana-mqtt-datasource
        jsonData:
          uri: "tcp://mosquitto:1883"
          tlsAuth: false
          clientID: formulatel_grafana
          isDefault: true
      - name: formulatel_psql
        type: postgres
        url: timescaledb:5432
        user: postgres
        secureJsonData:
          password: 'postgres'
        jsonData:
          database: postgres
          sslmode: 'disable'
          maxOpenConns: 100
          maxIdleConns: 100
          maxIdleConnsAuto: true
          connMaxLifetime: 14400
          postgresVersion: 1800
          timescaledb: true
      - name: formulatel_jaeger
        type: jaeger
        url: http://jaeger:16686

