grafana.ini:
  auth.anonymous:
    enabled: true
    org_role: Admin

plugins:
  - grafana-mqtt-datasource

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: formulatel_mqtt
        type: grafana-mqtt-datasource
        jsonData:
          uri: "tcp://mosquitto:1883"
          tlsAuth: false
          clientID: formulatel_grafana
          isDefault: true

# having trouble with this, or maybe my dashboard JSON is no good
dashboards:
  default:
    formulatel_test:
      file: test_dashboard.json
