externalAccess:
  enabled: true
  controller:
    service:
      type: NodePort
  broker:
    service:
      type: NodePort
  autoDiscovery:
    enabled: true
rbac:
  create: true
serviceAccount:
  create: true
controller:
  automountServiceAccountToken: true
broker:
  automountServiceAccountToken: true
listeners: # TODO: probably shouldn't be plaintext
  client:
    protocol: 'PLAINTEXT'
  controller:
    protocol: 'PLAINTEXT'
  external:
    protocol: 'PLAINTEXT'