apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "formulatel.fullname" . }}-grafana-ingress
  namespace: {{ .Values.global.namespace }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.grafana_ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.grafana_ingress.service_name }}
                port:
                  number: {{ .Values.grafana_ingress.port }}