# ---
# apiVersion: ctlptl.dev/v1alpha1
# kind: Registry
# name: ctlptl-registry
# port: 5005
---
# this yaml is to be used as `ctlptl apply -f cluster.yml` to bootstrap a k8s cluster using `kind`
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctl-formulatel
name: kind-formulatel
kindV1Alpha4Cluster:
  name: kind-formulatel
  nodes:
    - role: control-plane
      extraMounts:
        - hostPath: /sys/fs/bpf
          containerPath: /sys/fs/bpf
          propagation: Bidirectional # may not be needed (none of it is, probably)