apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: formulatel
  labels:
    app: persist
  name: persist
spec:
  selector:
    matchLabels:
      app: persist
  template:
    metadata:
      labels:
        app: persist
    spec:
      containers:
        - name: persist
          image: persist:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: TIMESCALE_DSN
            value: 'postgres://postgres:postgres@timescaledb:5432/postgres?sslmode=disable'
          - name: MQTT_BROKER
            value: 'tcp://mosquitto:1883'
          resources:
            requests:
              cpu: 250m
              memory: 512Mi