---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: formulatel
  labels:
    app: rpc
    opentelemetry.io/name: formulatel-rpc
    app.kubernetes.io/instance: formulatel
    app.kubernetes.io/component: rpc
    app.kubernetes.io/name: formulatel-rpc
    app.kubernetes.io/part-of: formulatel
  name: rpc
spec:
  selector:
    matchLabels:
      app: rpc
  template:
    metadata:
      labels:
        app: rpc
        opentelemetry.io/name: formulatel-rpc
        app.kubernetes.io/instance: formulatel
        app.kubernetes.io/component: rpc
        app.kubernetes.io/name: formulatel-rpc
    spec:
      containers:
        - name: rpc
          image: formulatel_rpc:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: OTEL_SERVICE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.labels['app.kubernetes.io/component']
          - name: OTEL_COLLECTOR_NAME
            value: 'formulatel-otelcol'
          - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
            value: cumulative
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://$(OTEL_COLLECTOR_NAME):4317
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name=$(OTEL_SERVICE_NAME),service.namespace=formulatel
          ports:
            - containerPort: 29292
              name: tcp-rpc
              protocol: TCP
          # readinessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     port: 27543
          #     scheme: UDP
          # livenessProbe:
          #   failureThreshold: 3
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   successThreshold: 1
          #   udpSocket:
          #     port: 27543
          #   timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: formulatel
  name: rpc
spec:
  ports:
    - port: 29292
      protocol: TCP
      targetPort: 29292
  selector:
    app: rpc