on:
  push:
    branches:
      - release-testing

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-formulatel

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v5
        with:
          # optional. customize path to release-please-config.json
          config-file: release-please-config.json
          # optional. customize path to .release-please-manifest.json
          manifest-file: .release-please-manifest.json