on:
  push:
    branches:
      - release-testing

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

name: release-formulatel

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v5